# Generated by Django 2.2.2 on 2019-09-29 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('presentationpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='PresentationPage',
        ),
    ]
