# Generated by Django 2.2.2 on 2019-09-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0002_auto_20190928_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationpage',
            name='firstText',
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='textContact',
            field=models.TextField(default=None, help_text='Enter section text'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='textNotes',
            field=models.TextField(default=None, help_text='Enter section text'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='textVision',
            field=models.TextField(default=None, help_text='Enter text under the main overlay'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='titleContact',
            field=models.TextField(default=None, help_text='Enter section title'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='titleNotes',
            field=models.TextField(default=None, help_text='Enter section title'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='titleVision',
            field=models.TextField(default=None, help_text='Enter title under the main overlay'),
        ),
    ]
