# Generated by Django 2.2.2 on 2019-09-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0003_auto_20190929_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='textFooter',
            field=models.TextField(default=None, help_text='Enter section text'),
        ),
    ]
