# Generated by Django 2.2.2 on 2019-09-30 03:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0004_presentationpage_textfooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationpage',
            name='textContact',
            field=wagtail.core.fields.RichTextField(default=None, help_text='Enter section text'),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='textNotes',
            field=wagtail.core.fields.RichTextField(default=None, help_text='Enter section text'),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='textVision',
            field=wagtail.core.fields.RichTextField(default=None, help_text='Enter text under the main overlay'),
        ),
    ]
