# Generated by Django 2.2.2 on 2019-10-05 02:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0006_auto_20190929_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='bodyd',
            field=wagtail.core.fields.StreamField([('vision', wagtail.core.blocks.TextBlock(default='a'))], blank=True),
        ),
    ]
