# Generated by Django 2.2.2 on 2019-10-05 03:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0007_presentationpage_bodyd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationpage',
            name='bodyd',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='textContact',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='textFooter',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='textNotes',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='textVision',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='titleContact',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='titleNotes',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='titleVision',
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='visionTitle',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Vision'))], blank=True),
        ),
    ]
