# Generated by Django 2.2.2 on 2019-10-05 03:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0008_auto_20191004_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='visionText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Vision'))], blank=True),
        ),
    ]
