# Generated by Django 2.2.2 on 2019-10-05 04:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0009_presentationpage_visiontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='missionText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Mission'))], blank=True),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='missionTitle',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Mission'))], blank=True),
        ),
    ]
