# Generated by Django 2.2.2 on 2019-10-05 04:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0010_auto_20191005_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='notesText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Notes'))], blank=True),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='notesTitle',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Notes'))], blank=True),
        ),
    ]
