# Generated by Django 2.2.2 on 2019-10-05 04:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0011_auto_20191005_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='contactusText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Contact Us'))], blank=True),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='contactusTitle',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Contact Us'))], blank=True),
        ),
    ]
