# Generated by Django 2.2.2 on 2019-10-06 00:16

from django.db import migrations
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0012_auto_20191005_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='video',
            field=wagtail.core.fields.StreamField([('video', wagtail.embeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
