# Generated by Django 2.2.2 on 2019-10-06 01:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0013_presentationpage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationpage',
            name='video',
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='videoURL',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.CharBlock())], blank=True),
        ),
    ]
