# Generated by Django 2.2.2 on 2020-01-31 16:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('presentationpage', '0014_auto_20191005_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('visionTitle', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Vision'))], blank=True)),
                ('visionText', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Vision'))], blank=True)),
                ('explainTitle', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Explain'))], blank=True)),
                ('explainText', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Explain'))], blank=True)),
                ('sellingTitle', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Why this is for you'))], blank=True)),
                ('sellingText', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Why this is for you'))], blank=True)),
                ('contactusTitle', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Contact Us'))], blank=True)),
                ('contactusText', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(default='Contact Us'))], blank=True)),
                ('videoURL', wagtail.core.fields.StreamField([('video', wagtail.core.blocks.CharBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
