# Generated by Django 2.2.2 on 2020-02-13 21:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0015_intropage'),
    ]

    operations = [
        migrations.AddField(
            model_name='intropage',
            name='notesText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(default='Learn more', features=['h2', 'bold', 'italic', 'link', 'ul', 'hr']))], blank=True),
        ),
        migrations.AddField(
            model_name='intropage',
            name='notesTitle',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(default='Learn more'))], blank=True),
        ),
        migrations.AlterField(
            model_name='intropage',
            name='explainText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(default='Explain', features=['h2', 'bold', 'italic', 'link', 'ul', 'hr']))], blank=True),
        ),
        migrations.AlterField(
            model_name='intropage',
            name='sellingText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(default='Why this is for you', features=['h2', 'bold', 'italic', 'link', 'ul', 'hr']))], blank=True),
        ),
    ]
