# Generated by Django 2.2.2 on 2020-02-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0016_auto_20200213_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intropage',
            name='videoURL',
        ),
    ]
