# Generated by Django 2.2.2 on 2020-03-16 22:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0017_remove_intropage_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intropage',
            name='visionText',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(default='Vision', features=['h2', 'bold', 'italic', 'link', 'ul', 'hr']))], blank=True),
        ),
    ]
