# Generated by Django 2.2.2 on 2020-04-28 21:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationpage', '0018_auto_20200316_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationpage',
            name='videoURL',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.StructBlock([('videoURL', wagtail.core.blocks.CharBlock()), ('videoTitle', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
