# Generated by Django 2.2.2 on 2020-05-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocmsvideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocmsvideo_data', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.AddField(
            model_name='data',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocmsvideo.Video'),
        ),
    ]
