# Generated by Django 2.2.2 on 2020-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0002_auto_20200528_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='video',
        ),
        migrations.AddField(
            model_name='data',
            name='video',
            field=models.ManyToManyField(to='djangocmsvideo.Video'),
        ),
    ]
