# Generated by Django 2.2.2 on 2020-05-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0003_auto_20200528_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_item', to='djangocmsvideo.Data'),
        ),
    ]
