# Generated by Django 2.2.2 on 2020-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0004_auto_20200528_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
