# Generated by Django 2.2.2 on 2020-05-28 19:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0005_auto_20200528_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
