# Generated by Django 2.2.2 on 2020-05-28 21:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0006_auto_20200528_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
