# Generated by Django 2.2.2 on 2020-05-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0007_auto_20200528_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
