# Generated by Django 2.2.2 on 2020-05-28 22:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0008_remove_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
    ]
