# Generated by Django 2.2.2 on 2020-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0010_auto_20200528_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
