# Generated by Django 2.2.2 on 2020-06-01 17:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocmsvideo', '0011_auto_20200601_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
