# Generated by Django 2.2.2 on 2020-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
