# Generated by Django 2.2.2 on 2020-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_questioninstance_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninstance',
            name='answer',
            field=models.BooleanField(null=True),
        ),
    ]
