# Generated by Django 2.2.2 on 2020-05-20 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailySteps', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 5, 20))),
                ('stepsCompetitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.StepsCompetitor')),
            ],
        ),
    ]
