# Generated by Django 2.2.2 on 2020-05-21 17:20

import datetime
from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepscompetitor',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F(django.db.models.aggregates.Sum('dailysteps__dailySteps')))]},
        ),
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 21)),
        ),
    ]
