# Generated by Django 2.2.2 on 2020-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_auto_20200521_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepscompetitor',
            options={'ordering': ['-totalSteps']},
        ),
        migrations.AddField(
            model_name='stepscompetitor',
            name='totalSteps',
            field=models.IntegerField(default=0),
        ),
    ]
