# Generated by Django 2.2.2 on 2020-05-28 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_auto_20200527_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 28)),
        ),
    ]
