# Generated by Django 2.2.2 on 2020-06-01 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_auto_20200528_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 1)),
        ),
    ]
