# Generated by Django 2.2.2 on 2020-06-06 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_auto_20200601_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 6)),
        ),
    ]
