# Generated by Django 2.2.2 on 2020-08-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_auto_20200606_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 5)),
        ),
    ]
