# Generated by Django 2.2.2 on 2020-08-07 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_auto_20200806_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
    ]
