# Generated by Django 2.2.2 on 2020-08-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0010_auto_20200807_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
    ]
