# Generated by Django 2.2.2 on 2020-08-25 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0019_auto_20200823_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 25)),
        ),
    ]
