# Generated by Django 2.2.2 on 2020-12-21 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0021_auto_20200826_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 21)),
        ),
    ]
