# Generated by Django 2.2.2 on 2020-12-28 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0022_auto_20201221_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 28)),
        ),
    ]
