# Generated by Django 2.2.2 on 2021-01-04 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0024_auto_20201230_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
    ]
