# Generated by Django 2.2.2 on 2021-01-05 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0025_auto_20210104_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 5)),
        ),
    ]
