# Generated by Django 2.2.2 on 2021-01-21 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0026_auto_20210105_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 21)),
        ),
    ]
