# Generated by Django 2.2.2 on 2021-10-05 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0027_auto_20210121_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 5)),
        ),
    ]
