# Generated by Django 2.2.2 on 2023-11-17 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0028_auto_20211005_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysteps',
            name='addExtraPoints',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailysteps',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 17)),
        ),
    ]
