# Generated by Django 2.2.2 on 2019-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDistrictManager',
            field=models.BooleanField(default=False),
        ),
    ]
