# Generated by Django 2.2.2 on 2019-07-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_isdistrictmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isDistrictManager',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=1)),
                ('points', models.FloatField()),
                ('participants', models.PositiveIntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Districts')),
            ],
        ),
    ]
