# Generated by Django 2.2.2 on 2019-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190806_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=50),
        ),
    ]
