# Generated by Django 2.2.2 on 2019-08-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190806_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Teams'),
        ),
    ]
