# Generated by Django 2.2.2 on 2019-08-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190807_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Teams'),
        ),
    ]
