# Generated by Django 2.2.2 on 2019-08-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190807_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='color',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
