# Generated by Django 2.2.2 on 2019-08-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190807_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bmi',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cholesterol',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='diasBloodPressure',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='height',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isDiabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isPrediabetic',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sysBloodPressure',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='waistSize',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='weight',
            field=models.FloatField(default=None),
        ),
    ]
