# Generated by Django 2.2.2 on 2019-08-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190809_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='sex',
            new_name='gender',
        ),
    ]
