# Generated by Django 2.2.2 on 2019-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190811_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bmi',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cholesterol',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='diasBloodPressure',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='height',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='isPrediabetic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sysBloodPressure',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='waistSize',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='weight',
            field=models.FloatField(default=None, null=True),
        ),
    ]
