# Generated by Django 2.2.2 on 2019-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190811_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='isDiabetic',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
