# Generated by Django 2.2.2 on 2019-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
