# Generated by Django 2.2.2 on 2019-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_districts_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dailyPoints',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='historyQuestions',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='historyPoints',
            field=models.TextField(default=None, null=True),
        ),
    ]
