# Generated by Django 2.2.2 on 2019-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190820_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='historyQuestions',
            field=models.TextField(default='[]', null=True),
        ),
    ]
