# Generated by Django 2.2.2 on 2019-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190829_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='historyPoints',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dailyPoints',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='historyPoints',
            field=models.TextField(default='[]', null=True),
        ),
    ]
