# Generated by Django 2.2.2 on 2019-09-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190903_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='activityLevel',
            field=models.FloatField(choices=[('Sedentary', 1.2), ('Light Active', 1.375), ('Moderately Active', 1.55), ('Active', 1.725)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bmr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='carbs',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fats',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isFatLoss',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isMuscleGain',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='proteins',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='totalDailyEnergyExp',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
