# Generated by Django 2.2.2 on 2019-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190910_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='energyConsumption',
            field=models.FloatField(default=None, null=True),
        ),
    ]
