# Generated by Django 2.2.2 on 2019-09-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_teacher_energyconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='daysLeft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isIndividualAccount',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isTeacherActive',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subscriptionType',
            field=models.CharField(choices=[('Monthly', 'Monthly')], default=None, max_length=50, null=True),
        ),
    ]
