# Generated by Django 2.2.2 on 2019-09-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190915_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subscriptionType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Subscriptions'),
        ),
    ]
