# Generated by Django 2.2.2 on 2019-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190915_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='days',
            new_name='length',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='unit',
            field=models.CharField(choices=[('M', 'Months'), ('Y', 'Years')], default='M', max_length=1),
        ),
    ]
