# Generated by Django 2.2.2 on 2019-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190916_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='daysLeft',
        ),
        migrations.AddField(
            model_name='teacher',
            name='goodUntil',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='activityLevel',
            field=models.FloatField(choices=[(1.2, 'Sedentary'), (1.375, 'Light Active'), (1.55, 'Moderately Active'), (1.725, 'Active')], default=None, null=True),
        ),
    ]
