# Generated by Django 2.2.2 on 2019-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190920_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='goodUntil',
            field=models.DateField(auto_now_add=True),
        ),
    ]
