# Generated by Django 2.2.2 on 2019-09-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190920_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Districts'),
        ),
    ]
