# Generated by Django 2.2.2 on 2019-09-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190920_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('emailDomain', models.CharField(db_index=True, max_length=100)),
                ('points', models.FloatField(default=0)),
                ('participants', models.IntegerField(default=0)),
                ('historyPoints', models.TextField(default='[]', null=True)),
            ],
            options={
                'verbose_name_plural': 'Independent Districts',
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Districts'),
        ),
    ]
