# Generated by Django 2.2.2 on 2019-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190920_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndependentDistricts',
        ),
        migrations.AddField(
            model_name='districts',
            name='isIndependent',
            field=models.BooleanField(default=False),
        ),
    ]
