# Generated by Django 2.2.2 on 2019-09-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190920_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='isFatLoss',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='isMuscleGain',
        ),
        migrations.AddField(
            model_name='teacher',
            name='goal',
            field=models.CharField(choices=[('F', 'Fat Loss'), ('M', 'Muscle Gain')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='activityLevel',
            field=models.CharField(choices=[(1.2, 'Sedentary'), (1.375, 'Light Active'), (1.55, 'Moderately Active'), (1.725, 'Active')], default=None, max_length=1, null=True),
        ),
    ]
