# Generated by Django 2.2.2 on 2019-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190924_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='activityLevel',
            field=models.CharField(choices=[('S', 'Sedentary'), ('LA', 'Light Active'), ('MA', 'Moderately Active'), ('A', 'Active')], default=None, max_length=2, null=True),
        ),
    ]
