# Generated by Django 2.2.2 on 2019-09-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190924_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='goodUntil',
            field=models.DateField(default=None, null=True),
        ),
    ]
