# Generated by Django 2.2.2 on 2019-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190926_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isKeto',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastDiet',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nutritionDetails',
            field=models.TextField(default=None, null=True),
        ),
    ]
