# Generated by Django 2.2.2 on 2019-09-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20190927_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='isTeacherActive',
            new_name='processingSubscription',
        ),
    ]
