# Generated by Django 2.2.2 on 2019-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190927_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='processingSubscription',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
