# Generated by Django 2.2.2 on 2020-02-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20190928_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=50),
        ),
    ]
