# Generated by Django 2.2.2 on 2020-03-12 00:54

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 0, 54, 8, 724378, tzinfo=utc))),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default=None, upload_to=accounts.models.user_directory_path)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('mediaaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.MediaAccount')),
                ('image_field', models.ImageField(upload_to=accounts.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.mediaaccount',),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ManyToManyField(blank=True, to='accounts.ImageProfile'),
        ),
    ]
