# Generated by Django 2.2.2 on 2020-03-11 21:13

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200311_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='image_field',
            field=models.ImageField(upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 21, 13, 37, 658161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mediaaccount',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=accounts.models.user_directory_path),
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ImageProfile'),
        ),
    ]
