# Generated by Django 2.2.2 on 2020-03-16 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200311_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 22, 4, 27, 641503, tzinfo=utc)),
        ),
    ]
