# Generated by Django 2.2.2 on 2020-04-28 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200317_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 21, 8, 49, 847283, tzinfo=utc)),
        ),
    ]
