# Generated by Django 2.2.2 on 2020-05-04 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200428_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 45, 8, 275911, tzinfo=utc)),
        ),
    ]
