# Generated by Django 2.2.2 on 2020-05-04 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20200504_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 19, 37, 36, 560893, tzinfo=utc)),
        ),
    ]
