# Generated by Django 2.2.2 on 2020-05-06 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20200504_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 20, 34, 36, 662705, tzinfo=utc)),
        ),
    ]
