# Generated by Django 2.2.2 on 2020-05-08 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20200508_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 19, 31, 53, 384137, tzinfo=utc)),
        ),
    ]
