# Generated by Django 2.2.2 on 2020-05-12 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20200508_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 23, 37, 20, 874288, tzinfo=utc)),
        ),
    ]
