# Generated by Django 2.2.2 on 2020-05-20 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20200512_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 16, 29, 18, 770371, tzinfo=utc)),
        ),
    ]
