# Generated by Django 2.2.2 on 2020-05-20 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20200520_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 21, 10, 28, 931494, tzinfo=utc)),
        ),
    ]
