# Generated by Django 2.2.2 on 2020-05-21 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20200520_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 20, 20, 688551, tzinfo=utc)),
        ),
    ]
