# Generated by Django 2.2.2 on 2020-05-27 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20200521_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 7, 13, 475485, tzinfo=utc)),
        ),
    ]
