# Generated by Django 2.2.2 on 2020-05-27 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20200527_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 19, 11, 4, 296585, tzinfo=utc)),
        ),
    ]
