# Generated by Django 2.2.2 on 2020-05-28 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20200528_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 21, 37, 48, 698771, tzinfo=utc)),
        ),
    ]
