# Generated by Django 2.2.2 on 2020-06-01 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_auto_20200528_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 48, 53, 715736, tzinfo=utc)),
        ),
    ]
