# Generated by Django 2.2.2 on 2020-06-01 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_auto_20200601_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 17, 3, 53, 238547, tzinfo=utc)),
        ),
    ]
