# Generated by Django 2.2.2 on 2020-06-06 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_auto_20200601_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 22, 9, 24, 600296, tzinfo=utc)),
        ),
    ]
