# Generated by Django 2.2.2 on 2020-08-05 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_auto_20200805_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 19, 24, 29, 809791, tzinfo=utc)),
        ),
    ]
