# Generated by Django 2.2.2 on 2020-08-05 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_auto_20200805_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 19, 25, 43, 693401, tzinfo=utc)),
        ),
    ]
