# Generated by Django 2.2.2 on 2020-08-06 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_auto_20200805_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 20, 46, 41, 615153, tzinfo=utc)),
        ),
    ]
