# Generated by Django 2.2.2 on 2020-08-07 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_auto_20200806_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 14, 43, 11, 730756, tzinfo=utc)),
        ),
    ]
