# Generated by Django 2.2.2 on 2020-08-09 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20200807_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 1, 1, 102064, tzinfo=utc)),
        ),
    ]
