# Generated by Django 2.2.2 on 2020-08-09 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20200809_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 10, 45, 483736, tzinfo=utc)),
        ),
    ]
