# Generated by Django 2.2.2 on 2020-08-10 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_auto_20200809_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 16, 34, 53, 328724, tzinfo=utc)),
        ),
    ]
