# Generated by Django 2.2.2 on 2020-08-10 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20200810_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 18, 7, 45, 944992, tzinfo=utc)),
        ),
    ]
