# Generated by Django 2.2.2 on 2020-08-10 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20200810_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 21, 18, 25, 1156, tzinfo=utc)),
        ),
    ]
