# Generated by Django 2.2.2 on 2020-08-10 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20200810_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 21, 23, 20, 369736, tzinfo=utc)),
        ),
    ]
