# Generated by Django 2.2.2 on 2020-08-12 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20200810_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 19, 5, 43, 731014, tzinfo=utc)),
        ),
    ]
