# Generated by Django 2.2.2 on 2020-08-12 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_auto_20200812_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 21, 53, 24, 521204, tzinfo=utc)),
        ),
    ]
