# Generated by Django 2.2.2 on 2020-08-13 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_auto_20200812_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 19, 9, 11, 466031, tzinfo=utc)),
        ),
    ]
