# Generated by Django 2.2.2 on 2020-08-14 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20200813_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 14, 16, 47, 613811, tzinfo=utc)),
        ),
    ]
