# Generated by Django 2.2.2 on 2020-08-18 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_auto_20200814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 15, 25, 2, 554933, tzinfo=utc)),
        ),
    ]
