# Generated by Django 2.2.2 on 2020-08-21 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_auto_20200821_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 3, 17, 23, 65075, tzinfo=utc)),
        ),
    ]
