# Generated by Django 2.2.2 on 2020-08-23 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_auto_20200821_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 2, 48, 8, 554631, tzinfo=utc)),
        ),
    ]
