# Generated by Django 2.2.2 on 2020-08-25 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_auto_20200825_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 3, 0, 17, 482004, tzinfo=utc)),
        ),
    ]
