# Generated by Django 2.2.2 on 2020-12-21 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20200826_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='district',
        ),
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 32, 27, 494708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.School'),
        ),
        migrations.AddField(
            model_name='teams',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.School'),
        ),
    ]
