# Generated by Django 2.2.2 on 2020-12-28 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_auto_20201221_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Districts'),
        ),
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 19, 1, 47, 137606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple')], default=None, max_length=10, null=True),
        ),
    ]
