# Generated by Django 2.2.2 on 2020-12-30 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_auto_20201228_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 16, 9, 27, 254893, tzinfo=utc)),
        ),
    ]
