# Generated by Django 2.2.2 on 2021-01-04 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_auto_20201230_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 56, 33, 903452, tzinfo=utc)),
        ),
    ]
