# Generated by Django 2.2.2 on 2021-01-05 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_auto_20210105_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 20, 6, 51, 360007, tzinfo=utc)),
        ),
    ]
