# Generated by Django 2.2.2 on 2021-01-21 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_auto_20210105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 34, 24, 514823, tzinfo=utc)),
        ),
    ]
