# Generated by Django 2.2.2 on 2021-10-05 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_auto_20210121_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 0, 17, 55, 386957, tzinfo=utc)),
        ),
    ]
