# Generated by Django 2.2.2 on 2021-10-05 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_auto_20211005_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 19, 10, 53, 801275, tzinfo=utc)),
        ),
    ]
