# Generated by Django 2.2.2 on 2023-11-18 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_auto_20230910_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mediaaccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 11, 29, 38, 668507, tzinfo=utc)),
        ),
    ]
