# Generated by Django 2.2.2 on 2019-12-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0015_auto_20191108_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tag', models.ManyToManyField(to='content.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datePosted', models.DateTimeField()),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PathInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLevel', models.IntegerField(default=0)),
                ('dateStarted', models.DateTimeField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.Path')),
                ('workout', models.ManyToManyField(to='workoutgames.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='workout',
            field=models.ManyToManyField(to='workoutgames.Workout'),
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.PathInstance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
