# Generated by Django 2.2.2 on 2019-12-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workoutgames.models.media


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default=None, upload_to=workoutgames.models.media.user_directory_path)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='path',
            name='tag',
        ),
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImageWorkout',
            fields=[
                ('mediaworkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workoutgames.MediaWorkout')),
                ('image_field', models.ImageField(upload_to=workoutgames.models.media.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('workoutgames.mediaworkout',),
        ),
        migrations.CreateModel(
            name='VideoWorkout',
            fields=[
                ('mediaworkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workoutgames.MediaWorkout')),
                ('video_field', models.FileField(upload_to=workoutgames.models.media.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('workoutgames.mediaworkout',),
        ),
        migrations.AddField(
            model_name='workout',
            name='tag',
            field=models.ManyToManyField(to='workoutgames.Tag'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image_content',
            field=models.ManyToManyField(blank=True, to='workoutgames.ImageWorkout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_content',
            field=models.ManyToManyField(blank=True, to='workoutgames.VideoWorkout'),
        ),
    ]
