# Generated by Django 2.2.2 on 2019-12-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0002_auto_20191211_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workoutgames.PathInstance'),
        ),
    ]
