# Generated by Django 2.2.2 on 2019-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0003_auto_20191217_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='path',
        ),
        migrations.AddField(
            model_name='gamer',
            name='path',
            field=models.ManyToManyField(null=True, to='workoutgames.PathInstance'),
        ),
    ]
