# Generated by Django 2.2.2 on 2020-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0004_auto_20191217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='path',
            field=models.ManyToManyField(to='workoutgames.PathInstance'),
        ),
    ]
