# Generated by Django 2.2.2 on 2020-01-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0005_auto_20200123_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='currLevelPath',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='path',
            name='levelPath',
            field=models.IntegerField(default=1),
        ),
    ]
