# Generated by Django 2.2.2 on 2020-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0006_auto_20200131_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
