# Generated by Django 2.2.2 on 2020-02-14 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0007_workout_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='dailyCompletedWorkouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamer',
            name='dailyTimestampWorkoutCompleted',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 0, 0)),
        ),
    ]
