# Generated by Django 2.2.2 on 2020-08-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0008_auto_20200213_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='accessedPath',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='workoutgames.Path'),
        ),
    ]
