# Generated by Django 2.2.2 on 2020-08-07 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0010_auto_20200806_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='dailyTimestampWorkoutCompleted',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
