# Generated by Django 2.2.2 on 2020-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0011_auto_20200807_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='movements',
        ),
    ]
