# Generated by Django 2.2.2 on 2020-08-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0012_remove_workout_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='slug',
        ),
        migrations.CreateModel(
            name='WorkoutPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('G', 'Gym'), ('H', 'Home'), ('B', 'Both')], default='B', max_length=1)),
                ('image_content', models.ManyToManyField(blank=True, to='workoutgames.ImageWorkout')),
                ('movements', models.ManyToManyField(to='workoutgames.Movement')),
                ('video_content', models.ManyToManyField(blank=True, to='workoutgames.VideoWorkout')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='MovementInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_reps', models.IntegerField(default=0)),
                ('recommended_sets', models.IntegerField(default=0)),
                ('recommended_weight', models.FloatField(default=0)),
                ('completed_reps', models.IntegerField(default=0)),
                ('completed_sets', models.IntegerField(default=0)),
                ('used_weight', models.FloatField(default=0)),
                ('date_completed', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.Movement')),
                ('path_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.PathInstance')),
            ],
        ),
    ]
