# Generated by Django 2.2.2 on 2020-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0013_auto_20200810_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplace',
            name='movements',
            field=models.ManyToManyField(blank=True, to='workoutgames.Movement'),
        ),
    ]
