# Generated by Django 2.2.2 on 2020-08-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0014_auto_20200810_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplace',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='workoutplace',
            name='video_content',
        ),
    ]
