# Generated by Django 2.2.2 on 2020-08-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0015_auto_20200810_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplace',
            name='movements',
        ),
        migrations.AddField(
            model_name='movement',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workoutgames.WorkoutPlace'),
        ),
    ]
