# Generated by Django 2.2.2 on 2020-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0016_auto_20200810_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='circuit',
            field=models.IntegerField(default=1),
        ),
    ]
