# Generated by Django 2.2.2 on 2020-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0017_movement_circuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutplace',
            name='ßmovements',
            field=models.ManyToManyField(blank=True, to='workoutgames.Movement'),
        ),
    ]
