# Generated by Django 2.2.2 on 2020-08-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0018_auto_20200812_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplace',
            old_name='ßmovements',
            new_name='movements',
        ),
    ]
