# Generated by Django 2.2.2 on 2020-08-12 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0019_auto_20200812_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
