# Generated by Django 2.2.2 on 2020-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0020_movement_dateposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
