# Generated by Django 2.2.2 on 2020-08-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0021_movement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementtype',
            name='thumbnail_movement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_assigned', to='workoutgames.ImageWorkout'),
        ),
    ]
