# Generated by Django 2.2.2 on 2020-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0023_auto_20200821_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementtype',
            name='video_content',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
