# Generated by Django 2.2.2 on 2020-08-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0024_movementtype_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementinstance',
            name='completed_reps',
        ),
        migrations.RemoveField(
            model_name='movementinstance',
            name='used_weight',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_reps', models.IntegerField(default=0)),
                ('set_num', models.IntegerField(default=0)),
                ('used_weight', models.FloatField(default=0)),
                ('date_completed', models.DateTimeField()),
                ('movement_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutgames.MovementInstance')),
            ],
        ),
    ]
