# Generated by Django 2.2.2 on 2020-08-25 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0025_auto_20200823_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='thumbnail_path',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_assigned', to='workoutgames.ImageWorkout'),
        ),
    ]
