# Generated by Django 2.2.2 on 2020-12-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0026_path_thumbnail_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('element',)},
        ),
    ]
