# Generated by Django 2.2.2 on 2021-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutgames', '0027_auto_20201221_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='sortOrder',
            field=models.IntegerField(default=100),
        ),
    ]
