# Generated by Django 2.2.2 on 2019-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('date', models.DateField()),
                ('responses', models.PositiveIntegerField()),
                ('yes', models.PositiveIntegerField()),
                ('no', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
