# Generated by Django 2.2.2 on 2019-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='responses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='yes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
