# Generated by Django 2.2.2 on 2019-10-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date',
        ),
    ]
