# Generated by Django 2.2.2 on 2019-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_media_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
