# Generated by Django 2.2.2 on 2019-10-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_media__date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
