# Generated by Django 2.2.2 on 2019-10-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
