# Generated by Django 2.2.2 on 2019-10-09 01:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0006_delete_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
