# Generated by Django 2.2.2 on 2019-10-10 21:35

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20191008_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_field',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_field',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('datePosted', models.DateTimeField(validators=[content.models.validate_datetime])),
                ('slug', models.SlugField(unique=True)),
                ('media_content', models.ManyToManyField(to='content.Media')),
                ('tags', models.ManyToManyField(to='content.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='media_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='media_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Media'),
            preserve_default=False,
        ),
    ]
