# Generated by Django 2.2.2 on 2019-10-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20191010_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media_content',
        ),
        migrations.AddField(
            model_name='content',
            name='image_content',
            field=models.ManyToManyField(to='content.Image'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_content',
            field=models.ManyToManyField(to='content.Video'),
        ),
    ]
