# Generated by Django 2.2.2 on 2019-10-14 19:15

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0010_auto_20191010_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='added_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.ImageField(upload_to=content.models.user_directory_path),
        ),
    ]
