# Generated by Django 2.2.2 on 2019-10-25 16:41

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20191014_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=content.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_field',
            field=models.FileField(upload_to=content.models.user_directory_path),
        ),
    ]
