# Generated by Django 2.2.2 on 2019-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20191025_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_content',
            field=models.ManyToManyField(blank=True, to='content.Image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_content',
            field=models.ManyToManyField(blank=True, to='content.Video'),
        ),
    ]
