# Generated by Django 2.2.2 on 2020-02-21 22:18

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20191108_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Media')),
                ('doc_field', models.FileField(upload_to=content.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.media',),
        ),
        migrations.AddField(
            model_name='content',
            name='doc_content',
            field=models.ManyToManyField(blank=True, to='content.Document'),
        ),
    ]
