# Generated by Django 2.2.2 on 2020-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20200221_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_field',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
