# Generated by Django 2.2.2 on 2021-01-05 20:05

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20201221_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_field_old',
            field=models.FileField(blank=True, default=None, null=True, upload_to=content.models.user_directory_path),
        ),
    ]
