# Generated by Django 2.2.2 on 2021-01-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_video_video_field_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_field_old',
        ),
    ]
