# Generated by Django 2.2.2 on 2021-10-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_remove_video_video_field_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sortOrder',
            field=models.IntegerField(default=100),
        ),
    ]
